### ISSUE TITLE
Warning: Deprecation

### ISSUE THREAD

**Issue by FahimFBA** [fhsinchy/ignore#1]
During the installation process, a depreciation warning appears: 
`DEPRECATION: ignore is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`. 

Other than that, everything else works just fine.

**Comment by FahimFBA** [comment]
![image](https://github.com/fhsinchy/ignore/assets/64195132/b186b4f1-d427-45e5-bc3a-97c3692a3c68)

**Comment by fhsinchy** [comment]
Thanks for raising the issue. This is known to me and I decided to ignore it. Given the simplicity of the script, I didn't bother to write the TOML and chose to use an old setup script from my previous projects. If you're up for it, feel free to implement the TOML and send a pull request. I'd be happy to review that and merge with my codebase.
